allowBuilds:
  '@prisma/engines': true
  '@tailwindcss/oxide': true
  '@vercel/speed-insights': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
